import * as React from "react";
import PageLayout from "../components/page-layout";
import Banner from "../components/banner";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
 
 
 export const config: TemplateConfig = {
   name: "index",
 };
 
 
  export const getPath: GetPath<TemplateProps> = ({document}) => {
    return `index.html`;
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  return {
    title: "Home Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

  const Index: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
  const {
    _site, 
  } = document;

   return (
    <>
      <PageLayout >
        <Banner text="Home Page"></Banner>
        <div className="centered-container">
          <div className="section space-y-10 px-10">
              <h1 className="text-center">Welcome to Turtlehead Tacos!</h1>
              <div className="px-14 space-y-5">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
          </div>
        </div>
      </PageLayout>
    </>
   );
 };
 
 export default Index;
 